### ISSUE TITLE
fix merge conflicts with MergeLocChanges and develop

### ISSUE THREAD

**Issue by josiahw** [NUbots/robocup#54] opened 2013-06-12 02:16 UTC
you updated our everything, so fix all the issues :-P

**Comment by shannonfenn** [comment] 2013-06-12 02:17
Haha, some of the issues are due to behaviour being changed in both branches too.

**Comment by BrendanAnnable** [comment] 2013-06-12 18:27
Conflicts resolved and merged into develop, confirmed as compiling and running.

MergeLocChanges remains untouched.

**Closed as completed by BrendanAnnable** 2013-06-12 18:27 UTC
Labels: todo
